### PR TITLE
Accept DB config with implicit port

### LINKED ISSUE #38: Exception when database port is not specified
An exception occurs in case `$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['port']` is not specified:
```
[ TYPO3\CMS\Core\Error\Exception ]                                                                                                            
  PHP Warning: Undefined array key "port" in /var/www/html/vendor/pagemachine/typo3-phinx/Classes/Configuration/PhinxConfiguration.php line 34
```

We generally do not configure this value as the default value of `3306` is used as a fallback within Doctrine DBAL.

### PR DESCRIPTION
**Pull request by mbrodala**
Fixes #38

### CODE REVIEW

File: Classes/Configuration/PhinxConfiguration.php [hunk 1]
```diff
@@ -31,7 +31,7 @@ public function toArray(): array
                 'typo3' => [
                     'adapter' => 'mysql',
                     'host' => $connectionParameters['host'],
-                    'port' => $connectionParameters['port'],
+                    'port' => $connectionParameters['port'] ?? 3306,
```
Comment (dahaupt) [inline Classes/Configuration/PhinxConfiguration.php:34]: What about changing the default to `null`, as the database library (e.g. Doctrine) already provides a fallback. I can confirm, that it is working with `null` as well.

Comment (mbrodala) [reply Classes/Configuration/PhinxConfiguration.php:34]: Sounds reasonable and would make the config a bit more generic to support other `adapter`s in the future.
